services:
  shredhills:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY}
        - REACT_APP_FIREBASE_AUTH_DOMAIN=${REACT_APP_FIREBASE_AUTH_DOMAIN}
        - REACT_APP_FIREBASE_PROJECT_ID=${REACT_APP_FIREBASE_PROJECT_ID}
        - REACT_APP_FIREBASE_STORAGE_BUCKET=${REACT_APP_FIREBASE_STORAGE_BUCKET}
        - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
        - REACT_APP_FIREBASE_APP_ID=${REACT_APP_FIREBASE_APP_ID}
    container_name: shredhills
    restart: unless-stopped
    ports:
      - "3005:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shredhills.rule=Host(`${SHREDHILLS_DOMAIN}`)"
      - "traefik.http.routers.shredhills.entrypoints=https"
      - "traefik.http.routers.shredhills.tls=true"
      - "traefik.http.services.shredhills.loadbalancer.server.port=80"
    networks:
      - qcav-network1

networks:
  qcav-network1:
    external: true
